[database]
host = "127.0.0.1"
port = 3306
user = "sspanel_node"
password = "change-me"
database = "sspanel"

[node]
id = 121
check_rate = 60
speedtest_check_rate = 0

[panel]
url = "https://google.com"
key = "change-me"
type = 0
down_with_panel = 0
use_mysql = 1
mu_regex = "%5m%id.%suffix"
mu_suffix = "microsoft.com"

[v2ray]
config_path = "/etc/v2ray/config.json"
loglevel = "info"
restart_command = ["systemctl", "restart", "v2ray"]

[plugin]
cf_key = "bbbbbbbbbbbbbbbbbb"
cf_email = "v2ray@v2ray.com"
proxy_tcp = 0
ali_key = "sdfsdfsdfljlbjkljlkjsdfoiwje"
ali_secret = "jlsdflanljkljlfdsaklkjflsa"
cache_duration_sec = 60
html_path = ""

[runtime]
dry_run = true
print_config = true
